// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';SS
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```S
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKrU4Ktd_SnHfWsJW-tI0Y8Tp3LvFiKFs',
    appId: '1:680680257082:web:2acaac2e85c36b4623a703',
    messagingSenderId: '680680257082',
    projectId: 'university-graduation',
    authDomain: 'university-graduation.firebaseapp.com',
    storageBucket: 'university-graduation.firebasestorage.app',
    measurementId: 'G-10RYS96E8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4lNdYUa50DQZIy8lh-SgOIpAl8nk2f-c',
    appId: '1:680680257082:android:1ae021a82ccb555123a703',
    messagingSenderId: '680680257082',
    projectId: 'university-graduation',
    storageBucket: 'university-graduation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCodCwUR2iW7K7lLQXvxibt30bOvJ_KPw',
    appId: '1:680680257082:ios:7c096b22fc89dc2d23a703',
    messagingSenderId: '680680257082',
    projectId: 'university-graduation',
    storageBucket: 'university-graduation.firebasestorage.app',
    iosClientId: '680680257082-8e8phar2qog1ifblp82tjl8f7smn6d8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sepTwentythird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCodCwUR2iW7K7lLQXvxibt30bOvJ_KPw',
    appId: '1:680680257082:ios:7c096b22fc89dc2d23a703',
    messagingSenderId: '680680257082',
    projectId: 'university-graduation',
    storageBucket: 'university-graduation.firebasestorage.app',
    iosClientId: '680680257082-8e8phar2qog1ifblp82tjl8f7smn6d8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sepTwentythird',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKrU4Ktd_SnHfWsJW-tI0Y8Tp3LvFiKFs',
    appId: '1:680680257082:web:6aaf557c8f7f12ae23a703',
    messagingSenderId: '680680257082',
    projectId: 'university-graduation',
    authDomain: 'university-graduation.firebaseapp.com',
    storageBucket: 'university-graduation.firebasestorage.app',
    measurementId: 'G-QL24KRX01T',
  );
}
